### ISSUE TITLE
Add a chapter for "How to use another version"

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/docs-de#2]
Add a chapter for using another version for example a Hotifx for testing, with composer. 

"metamodels/core": "dev-hotfix-clearall as 2.0.0"

**Comment by zonky2** [comment]
"Hotifx" werde ich mit aufnehmen ;-)

**Comment by zonky2** [comment]
http://metamodels.readthedocs.org/de/latest/manual/install.html#test-von-speziellen-bundles-via-composer
